version: "3"
services:
  fluentd-logger:
    restart: always
    build: fluentd_coralogix_image
    environment:
      PRIVATE_KEY: ${PRIVATE_KEY:-XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX}
      APP_NAME: ${APP_NAME:-default_app_name}
      SUB_SYSTEM: ${SUB_SYSTEM:-default_subsystem_name}
    container_name: fluentd-coralogix
    ports:
      - "24224:24224"
      - "24224:24224/udp"
      - "9880:9880"
      - "5140:5140/udp"
    volumes:
      - fluentd-logs:/fluentd/log

volumes:
  fluentd-logs: